package com.mahavastu.advisor.model;

public enum LevelEnum
{
    LEVEL_1_A_ENTRANCE,
    LEVEL_1_B_PRAKRITI_BUILDING,
    LEVEL_1_B_PRAKRITI_OF_PERSON,
    LEVEL_1_B_SUGGESTION_FOR_PRAKRITI,
    LEVEL_1_C_DISHA_BAL,
    LEVEL_1_D_FIVE_ELEMENTS,
    LEVEL_1_E_ACTIVITY,
    LEVEL_1_F_UTILITY,
    LEVEL_1_G_OBJECTS,
    LEVEL_1_H_REMEDIES,
    LEVEL_1_I_ASTRO_1,
    LEVEL_1_I_ASTRO_2,
    LEVEL_1_I_ASTRO_3,
    LEVEL_1_J_MARMA,
    LEVEL_1_J_DEVTA_2,
    LEVEL_1_K_INTUITIVE,
    LEVEL_1_K_DEVTA_1;
    ;
}
